Repository esrlabs/northstar, pull requests merged in 2022-08, with the labels that each got.

#765 Create IPC and UTS namespace for containers
  README.md
  doc/container-startup.png
  doc/container-startup.puml
  northstar-runtime/src/runtime/fork/init/mod.rs
Labels: enhancement

#763 Replace install assert with buffer size logic
  northstar-runtime/src/runtime/console/mod.rs
Labels: bug, audit_0822

#775 Kill process on seccomp violation
  README.md
  northstar-runtime/src/seccomp/bpf.rs
Labels: audit_0822

#776 Include NPK comment block in signature
  northstar-runtime/src/npk/npk.rs
Labels: audit_0822

#780 Network configuration
  examples/inspect/manifest.yaml
  examples/netns/manifest.yaml
  examples/redis-client/manifest.yaml
  examples/redis/manifest.yaml
  examples/redis/src/main.rs
  examples/token-client/manifest.yaml
  examples/token-server/manifest.yaml
  northstar-runtime/src/npk/manifest/io.rs
  northstar-runtime/src/npk/manifest/mod.rs
  northstar-runtime/src/npk/manifest/network.rs
  northstar-runtime/src/npk/manifest/validation.rs
  northstar-runtime/src/runtime/fork/init/builder.rs
  northstar-runtime/src/runtime/fork/init/mod.rs
Labels: enhancement, audit_0822

#781 Console extensions
  README.md
  android/northstar.toml
  doc/console.md
  northstar-runtime/src/npk/manifest/console.rs
  northstar-runtime/src/runtime/config.rs
  northstar-runtime/src/runtime/console/mod.rs
  northstar-runtime/src/runtime/mod.rs
  northstar-tests/src/runtime.rs
  northstar-tests/tests/console.rs
  northstar.toml
Labels: audit_0822

#777 Container IO refactoring
  .github/workflows/ci.yml
  README.md
  doc/container-startup.png
  doc/container-startup.puml
  northstar-runtime/Cargo.toml
  northstar-runtime/src/runtime/fork/forker/channel.rs
  northstar-runtime/src/runtime/fork/forker/messages.rs
  northstar-runtime/src/runtime/fork/forker/mod.rs
  northstar-runtime/src/runtime/fork/forker/process.rs
  northstar-runtime/src/runtime/fork/init/mod.rs
  northstar-runtime/src/runtime/fork/util.rs
  northstar-runtime/src/runtime/io.rs
  northstar-runtime/src/runtime/ipc/framed_stream.rs
  northstar-runtime/src/runtime/ipc/mod.rs
  northstar-runtime/src/runtime/ipc/owned_fd.rs
  northstar-runtime/src/runtime/ipc/socket_pair.rs
  northstar-runtime/src/runtime/state.rs
Labels: audit_0822
